name: Keep Alive Streamlit

on:
  schedule:
    # Se ejecuta todos los días a las 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente para probar

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"

      - name: Commit vacío para refrescar actividad
        run: |
          git commit --allow-empty -m "Refresco diario de actividad para Streamlit Cloud"
          git push
          
