[theme]
base = "light"
primaryColor = "#00008B"

[client]
# Cambia el modo de la barra de herramientas a "minimal" o "viewer"
# "minimal" oculta la mayor√≠a de las opciones externas
toolbarMode = "minimal"

[ui]
# Oculta la barra superior donde aparece el estado de "Running"
hideTopBar = true
